import {
  Activity,
  Bed,
  Briefcase,
  Cloud,
  CloudRain,
  DollarSign,
  Dumbbell,
  Flame,
  Frown,
  Heart,
  Home,
  Meh,
  Moon,
  Newspaper,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Users,
  Utensils,
  Waves,
  Wind,
  Zap,
} from "lucide-react";

export const moods = (t: any) => [
  {
    id: 1,
    name: t("moodTracker.moods.joyful.name"),
    icon: Sun,
    color: "from-yellow-400 to-orange-500",
    bgColor: "bg-gradient-to-br from-yellow-400 via-orange-400 to-orange-500",
    lightBg: "bg-yellow-50",
    iconColor: "text-yellow-500",
    description: "Feeling energetic, happy, and full of life",
    suggestedActivities: [
      "Take a walk in nature",
      "Call a friend or loved one",
      "Listen to upbeat music",
      "Dance or move your body",
    ],
    breathingPattern: "normal",
    affirmation: "I embrace the joy in my life and share it with others.",
    particles: "sunshine",
    animation: "bounce",
    primaryColor: "#F59E0B",
    secondaryColor: "#FDE68A",
    effectIcon: Star,
  },
  {
    id: 2,
    name: t("moodTracker.moods.content.name"),
    icon: Heart,
    color: "from-green-400 to-blue-500",
    bgColor: "bg-gradient-to-br from-green-400 via-emerald-400 to-blue-500",
    lightBg: "bg-green-50",
    iconColor: "text-green-500",
    description: "Peaceful, satisfied, and at ease with yourself",
    suggestedActivities: [
      "Practice meditation",
      "Read a good book",
      "Write in a gratitude journal",
      "Enjoy a warm cup of tea",
    ],
    breathingPattern: "calm",
    affirmation: "I am at peace with myself and my surroundings.",
    particles: "gentle",
    animation: "float",
    primaryColor: "#10B981",
    secondaryColor: "#A7F3D0",
    effectIcon: Waves,
  },
  {
    id: 3,
    name: t("moodTracker.moods.neutral.name"),
    icon: Meh,
    color: "from-gray-400 to-gray-600",
    bgColor: "bg-gradient-to-br from-gray-400 via-slate-400 to-gray-600",
    lightBg: "bg-gray-50",
    iconColor: "text-gray-500",
    description: "Feeling balanced, neither particularly good nor bad",
    suggestedActivities: [
      "Practice mindfulness",
      "Do light stretching",
      "Journal your thoughts",
      "Take a mindful walk",
    ],
    breathingPattern: "normal",
    affirmation:
      "I accept my current state and remain open to what comes next.",
    particles: "minimal",
    animation: "steady",
    primaryColor: "#6B7280",
    secondaryColor: "#D1D5DB",
    effectIcon: Wind,
  },
  {
    id: 4,
    name: t("moodTracker.moods.anxious.name"),
    icon: Zap,
    color: "from-orange-400 to-red-500",
    bgColor: "bg-gradient-to-br from-orange-400 via-red-400 to-red-500",
    lightBg: "bg-orange-50",
    iconColor: "text-orange-500",
    description: "Feeling worried, stressed, or overwhelmed",
    suggestedActivities: [
      "Practice deep breathing",
      "Try progressive muscle relaxation",
      "Use grounding techniques",
      "Listen to calming music",
    ],
    breathingPattern: "calming",
    affirmation:
      "This feeling is temporary. I am safe and I can handle this moment.",
    particles: "electric",
    animation: "pulse",
    primaryColor: "#F97316",
    secondaryColor: "#FDBA74",
    effectIcon: Zap,
  },
  {
    id: 5,
    name: t("moodTracker.moods.sad.name"),
    icon: Frown,
    color: "from-blue-400 to-purple-600",
    bgColor: "bg-gradient-to-br from-blue-400 via-indigo-500 to-purple-600",
    lightBg: "bg-blue-50",
    iconColor: "text-blue-500",
    description: "Feeling down, melancholy, or emotionally low",
    suggestedActivities: [
      "Practice self-care",
      "Gentle movement or yoga",
      "Talk to someone you trust",
      "Watch something comforting",
    ],
    breathingPattern: "deep",
    affirmation:
      "It's okay to feel sad. My emotions are valid and will pass with time.",
    particles: "rain",
    animation: "drift",
    primaryColor: "#3B82F6",
    secondaryColor: "#93C5FD",
    effectIcon: CloudRain,
  },
  {
    id: 6,
    name: t("moodTracker.moods.angry.name"),
    icon: Zap,
    color: "from-red-500 to-pink-600",
    bgColor: "bg-gradient-to-br from-red-500 via-rose-500 to-pink-600",
    lightBg: "bg-red-50",
    iconColor: "text-red-500",
    description: "Feeling frustrated, irritated, or mad",
    suggestedActivities: [
      "Physical exercise",
      "Write out your feelings",
      "Count to ten slowly",
      "Take a cold shower",
    ],
    breathingPattern: "releasing",
    affirmation:
      "I acknowledge my anger and choose how to respond to it constructively.",
    particles: "fire",
    animation: "shake",
    primaryColor: "#EF4444",
    secondaryColor: "#FCA5A5",
    effectIcon: Flame,
  },
  {
    id: 7,
    name: t("moodTracker.moods.excited.name"),
    icon: Smile,
    color: "from-yellow-300 to-pink-500",
    bgColor: "bg-gradient-to-br from-yellow-300 via-pink-400 to-pink-500",
    lightBg: "bg-pink-50",
    iconColor: "text-pink-500",
    description: "Feeling enthusiastic, eager, and full of anticipation",
    suggestedActivities: [
      "Channel energy into creativity",
      "Share your excitement with others",
      "Plan your next steps",
      "Start a new project",
    ],
    breathingPattern: "energizing",
    affirmation: "I embrace this positive energy and direct it purposefully.",
    particles: "sparkle",
    animation: "vibrate",
    primaryColor: "#EC4899",
    secondaryColor: "#F9A8D4",
    effectIcon: Sparkles,
  },
  {
    id: 8,
    name: t("moodTracker.moods.tired.name"),
    icon: Moon,
    color: "from-indigo-400 to-blue-700",
    bgColor: "bg-gradient-to-br from-indigo-400 via-blue-500 to-blue-700",
    lightBg: "bg-indigo-50",
    iconColor: "text-indigo-500",
    description: "Feeling fatigued, exhausted, or low on energy",
    suggestedActivities: [
      "Take a short nap",
      "Gentle stretching",
      "Prioritize rest and recovery",
      "Practice relaxation techniques",
    ],
    breathingPattern: "restful",
    affirmation: "I honor my body's need for rest and recovery.",
    particles: "dreamy",
    animation: "slow",
    primaryColor: "#6366F1",
    secondaryColor: "#C7D2FE",
    effectIcon: Snowflake,
  },
];

export const emotionTriggers = (t: any) => [
  {
    label: t("moodTracker.triggers.work"),
    icon: Briefcase,
    color: "text-blue-600",
    bg: "bg-blue-50",
    category: "external",
  },
  {
    label: t("moodTracker.triggers.relationships"),
    icon: Heart,
    color: "text-pink-600",
    bg: "bg-pink-50",
    category: "social",
  },
  {
    label: t("moodTracker.triggers.health"),
    icon: Activity,
    color: "text-green-600",
    bg: "bg-green-50",
    category: "physical",
  },
  {
    label: t("moodTracker.triggers.finances"),
    icon: DollarSign,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    category: "external",
  },
  {
    label: t("moodTracker.triggers.socialMedia"),
    icon: Smartphone,
    color: "text-purple-600",
    bg: "bg-purple-50",
    category: "digital",
  },
  {
    label: t("moodTracker.triggers.news"),
    icon: Newspaper,
    color: "text-orange-600",
    bg: "bg-orange-50",
    category: "digital",
  },
  {
    label: t("moodTracker.triggers.weather"),
    icon: Cloud,
    color: "text-sky-600",
    bg: "bg-sky-50",
    category: "environmental",
  },
  {
    label: t("moodTracker.triggers.sleep"),
    icon: Bed,
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    category: "physical",
  },
  {
    label: t("moodTracker.triggers.exercise"),
    icon: Dumbbell,
    color: "text-red-600",
    bg: "bg-red-50",
    category: "physical",
  },
  {
    label: t("moodTracker.triggers.food"),
    icon: Utensils,
    color: "text-yellow-600",
    bg: "bg-yellow-50",
    category: "physical",
  },
  {
    label: t("moodTracker.triggers.family"),
    icon: Home,
    color: "text-teal-600",
    bg: "bg-teal-50",
    category: "social",
  },
  {
    label: t("moodTracker.triggers.friends"),
    icon: Users,
    color: "text-cyan-600",
    bg: "bg-cyan-50",
    category: "social",
  },
];
